Repository igalklebanov/kysely-surrealdb, pull requests merged in 2022-10, with the labels that each got.

#1 fix(README): resolve minor typo
  README.md
Labels: documentation

#2 add `RelateQueryBuilder`.
  src/dialect/http/http-connection.ts
  src/dialect/http/http-dialect.ts
  src/dialect/http/http-types.ts
  src/index.ts
  src/operation-node/operation-node.ts
  src/operation-node/relate-query-node.ts
  src/parser/create-object-parser.ts
  src/parser/create-set-parser.ts
  src/parser/vertex-expression-parser.ts
  src/query-builder/create-query-builder.ts
  src/query-builder/relate-query-builder.ts
  src/query-compiler/query-compiler.ts
  src/surreal-kysely.ts
  src/util/surreal-types.ts
  tests/nodejs/surreal-kysely.test.ts
  tests/nodejs/surreal-kysely/create.test.ts
  tests/nodejs/surreal-kysely/relate.test.ts
  tests/nodejs/surreal-kysely/shared.ts
Labels: enhancement

#3 add ts docs everywhere.
  src/index.ts
  src/query-builder/create-query-builder.ts
  src/query-builder/relate-query-builder.ts
  src/query-builder/return-interface.ts
  src/query-builder/set-content-interface.ts
  src/surreal-kysely.ts
Labels: documentation, enhancement

#5 enhance `SurrealKysely.relate` api.
  README.md
  src/operation-node/operation-node.ts
  src/operation-node/relate-query-node.ts
  src/operation-node/vertex-node.ts
  src/parser/vertex-expression-parser.ts
  src/query-builder/relate-query-builder.ts
  src/query-compiler/query-compiler.ts
  src/surreal-kysely.ts
  src/util/object-utils.ts
  src/util/surreal-types.ts
  tests/nodejs/surreal-kysely/create.test.ts
  tests/nodejs/surreal-kysely/relate.test.ts
  tests/nodejs/surreal-kysely/shared.ts
Labels: enhancement
